Update requirements-up-to-date.yml

diff --git a/.github/workflows/requirements-up-to-date.yml b/.github/workflows/requirements-up-to-date.yml
--- a/.github/workflows/requirements-up-to-date.yml
+++ b/.github/workflows/requirements-up-to-date.yml
@@ -9,42 +9,38 @@ jobs:
   validate-dependencies:
     runs-on: ubuntu-latest
     steps:
-      - name: checkout code
+      - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: fetch all history
+      - name: Fetch all history
         run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
 
-      - name: check for changes in pyproject.toml and poetry.lock
+      - name: Check for changes in pyproject.toml and uv.lock
         id: check-deps
         run: |
-          echo "Checking pyproject.toml and poetry.lock for changes..."
+          echo "Checking pyproject.toml and uv.lock for changes..."
           BASE_BRANCH=${{ github.event.pull_request.base.ref }}
           HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
-          CHANGES=$(git diff --name-only origin/$BASE_BRANCH -- origin/$HEAD_BRANCH | grep -E "^(pyproject.toml|poetry.lock)$" || true)
+          CHANGES=$(git diff --name-only origin/$BASE_BRANCH -- origin/$HEAD_BRANCH | grep -E "^(pyproject.toml|uv.lock)$" || true)
           echo "Changed files: $CHANGES"
           if [ ! -z "$CHANGES" ]; then
-            echo "Checking if requirements.txt has also been updated..."
-            if ! git diff --name-only origin/$BASE_BRANCH -- origin/$HEAD_BRANCH | grep -q "requirements.txt"; then
-              echo "ERROR: pyproject.toml or poetry.lock has changed, but requirements.txt has not been updated."
-              echo "Please update requirements.txt by running 'make create-requirements'."
-              exit 1
-            fi
-          fi
+            echo "uv_updated=true" >> $GITHUB_ENV
+          else
+            echo "uv_updated=false" >> $GITHUB_ENV
 
-      - name: validate requirements.txt update
-        if: steps.check-deps.outputs.poetry_updated == 'true'
+      - name: Validate requirements.txt update
+        if: env.uv_updated == 'true'
         run: |
+          echo "Checking if requirements.txt has been updated..."
           BASE_BRANCH=${{ github.event.pull_request.base.ref }}
           HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
-          REQUIREMENTS_CHANGE=$(git diff --name-only origin/$BASE_BRANCH -- origin/$HEAD_BRANCH | grep -q "requirements.txt")
-          echo "requirements.txt changed: $REQUIREMENTS_CHANGE"
-          if [ ! -z "$REQUIREMENTS_CHANGE" ]; then
+          REQUIREMENTS_CHANGED=$(git diff --name-only origin/$BASE_BRANCH -- origin/$HEAD_BRANCH | grep -q "requirements.txt" && echo true || echo false)
+          if [ "$REQUIREMENTS_CHANGED" == "true" ]; then
             echo "requirements.txt updated correctly."
           else
-            echo "ERROR: pyproject.toml or poetry.lock has changed, but requirements.txt has not been updated."
+            echo "ERROR: pyproject.toml or uv.lock has changed, but requirements.txt has not been updated."
             echo "Please update requirements.txt by running 'make create-requirements'."
             exit 1
           fi
